/**
 * Public data-access layer over `_data/`: the accessors every page and route
 * handler uses. Read-only; SSG/ISR-friendly (all reads are build-time file
 * reads, memoised per process by `lib/data/load.ts`).
 *
 * Integrity is checked once, lazily, on first access: each accessor calls
 * `ensureVerified()`, which runs `assertDataIntegrity()` a single time and
 * throws if the datasets violate their invariants, so a broken `_data/` fails
 * `npm run build` rather than rendering wrong pages.
 *
 * Server-only (transitively uses `fs`): import from Server Components / route
 * handlers, never from a Client Component.
 */
import { selectReferencePrices } from '../price-gauge';
import {
  loadAllPriceHistory,
  loadElementCatalog,
  loadFluctuationsFile,
  loadMovements,
  loadNews,
  loadPolicyEvents,
  loadPriceRecords,
  loadRegulatoryNotices,
  loadSiteSettings,
  loadSourceBreakdown,
  loadSources,
} from './load';
import type {
  CategoryControl,
  CoverageTally,
  Element,
  ElementCategory,
  ElementCoverage,
  Fluctuation,
  MovementsFile,
  NewsItem,
  PolicyEvent,
  PremiumLeaderboardRow,
  PriceHistory,
  PriceRecord,
  ReferencePrices,
  RegulatoryNotice,
  RegulatorySnapshot,
  SiteSettings,
  Source,
  SourceBreakdown,
} from './types';
import { assertDataIntegrity } from './verify';

export type * from './types';
export { selectReferencePrices } from '../price-gauge';

/** Display/grouping order for the four element categories (matches the legacy grid). */
export const CATEGORY_ORDER: readonly ElementCategory[] = [
  'rare_earth_light',
  'rare_earth_heavy',
  'strategic_metal',
  'semiconductor_metal',
];

// Run the integrity assertions exactly once, on first data access.
const ensureVerified = (() => {
  let done = false;
  return () => {
    if (!done) {
      assertDataIntegrity();
      done = true;
    }
  };
})();

// ── Elements ───────────────────────────────────────────────────────────────

export function getElements(): Element[] {
  ensureVerified();
  return loadElementCatalog();
}

const elementBySymbol = (() => {
  let map: Map<string, Element> | undefined;
  return () =>
    (map ??= new Map(loadElementCatalog().map((e) => [e.symbol, e])));
})();

/** Case-sensitive lookup ('Dy', not 'dy'); symbols are used verbatim in URLs. */
export function getElementBySymbol(symbol: string): Element | null {
  ensureVerified();
  return elementBySymbol().get(symbol) ?? null;
}

/** Elements grouped by category, in `CATEGORY_ORDER`, preserving catalog order within each. */
export function getElementsByCategory(): Record<ElementCategory, Element[]> {
  ensureVerified();
  const grouped = {
    rare_earth_light: [],
    rare_earth_heavy: [],
    strategic_metal: [],
    semiconductor_metal: [],
  } as Record<ElementCategory, Element[]>;
  for (const el of loadElementCatalog()) grouped[el.category].push(el);
  return grouped;
}

// ── Prices ───────────────────────────────────────────────────────────────────

/** All price records, or only those for `symbol` (case-sensitive element symbol). */
export function getPriceRecords(symbol?: string): PriceRecord[] {
  ensureVerified();
  const records = loadPriceRecords();
  return symbol
    ? records.filter((r) => r.element_symbol === symbol)
    : records;
}

export function getPriceHistory(symbol: string): PriceHistory | null {
  ensureVerified();
  return loadAllPriceHistory().get(symbol) ?? null;
}

export function getFluctuation(symbol: string): Fluctuation | null {
  ensureVerified();
  return loadFluctuationsFile().elements[symbol] ?? null;
}

/**
 * Generation timestamp of the fluctuations dataset (RFC3339), the "data as of"
 * stamp on the dashboard. Read verbatim from `fluctuations.json` `generated_at`,
 * the freshest derived artefact the data pipeline writes (regenerated by the
 * weekly price-update and manual community-intake workflows; the old 6-hourly
 * regulatory-monitor cadence was removed).
 */
export function getDataGeneratedAt(): string {
  ensureVerified();
  return loadFluctuationsFile().generated_at;
}

/**
 * Retail/bulk reference prices and the retail premium for an element, via the
 * faithful port of `legacy/_includes/price-selection.html`.
 */
export function getReferencePrices(symbol: string): ReferencePrices {
  ensureVerified();
  return selectReferencePrices(loadPriceRecords(), symbol);
}

// ── Regulatory ───────────────────────────────────────────────────────────────

export function getRegulatoryNotices(): RegulatoryNotice[] {
  ensureVerified();
  return loadRegulatoryNotices();
}

export function getPolicyEvents(): PolicyEvent[] {
  ensureVerified();
  return loadPolicyEvents();
}

/**
 * Elements currently under an active Chinese export-licence requirement
 * (regulatory_status === 'active'). Mirrors the legacy regulatory banner's set,
 * distinct from `getControlledElementCount()` (the broader cn_export_control tally).
 */
export function getRegulatedElements(): Element[] {
  ensureVerified();
  return loadElementCatalog().filter((e) => e.regulatory_status === 'active');
}

/**
 * Every element with a non-'none' regulatory status (active OR suspended), in
 * atomic-number order: the set the regulatory tracker's element-filter strip
 * is built from (legacy regulatory.html: `regulatory_status != 'none'`).
 */
export function getRegulatedAndSuspendedElements(): Element[] {
  ensureVerified();
  return loadElementCatalog()
    .filter((e) => e.regulatory_status !== 'none')
    .sort((a, b) => a.atomic_number - b.atomic_number);
}

/** The auto-generated market-movements feed (config, state, and events). */
export function getMovements(): MovementsFile {
  ensureVerified();
  return loadMovements();
}

// ── Sources & breakdown ──────────────────────────────────────────────────────

export function getSources(): Source[] {
  ensureVerified();
  return loadSources();
}

export function getSourceBreakdown(): SourceBreakdown {
  ensureVerified();
  return loadSourceBreakdown();
}

/** Configurable thresholds + display labels (source_trust_tiers, etc.). */
export function getSiteSettings(): SiteSettings {
  ensureVerified();
  return loadSiteSettings();
}

// ── News ─────────────────────────────────────────────────────────────────────

export function getNews(): NewsItem[] {
  ensureVerified();
  return loadNews();
}

// ── Aggregate counts for the home / dashboard ────────────────────────────────

/** Element count per category, in `CATEGORY_ORDER`. */
export function getCategoryCounts(): Record<ElementCategory, number> {
  ensureVerified();
  const counts = {
    rare_earth_light: 0,
    rare_earth_heavy: 0,
    strategic_metal: 0,
    semiconductor_metal: 0,
  } as Record<ElementCategory, number>;
  for (const el of loadElementCatalog()) counts[el.category] += 1;
  return counts;
}

/**
 * Count of CN-export-controlled elements (cn_export_control === true), the
 * "CN-controlled" stat on the legacy home page (`_layouts/home.html`).
 */
export function getControlledElementCount(): number {
  ensureVerified();
  return loadElementCatalog().filter((e) => e.cn_export_control).length;
}

/**
 * Elements with both a retail and bulk reference price, ranked by retail premium
 * (retail ÷ bulk) descending. `limit` caps the rows (default: all).
 */
export function getPremiumLeaderboard(limit?: number): PremiumLeaderboardRow[] {
  ensureVerified();
  const records = loadPriceRecords();
  const rows: PremiumLeaderboardRow[] = [];
  for (const el of loadElementCatalog()) {
    const { retailRef, bulkRef, retailPremium } = selectReferencePrices(
      records,
      el.symbol,
    );
    if (retailRef && bulkRef && retailPremium !== null) {
      rows.push({
        symbol: el.symbol,
        name: el.name,
        category: el.category,
        retail_usd_per_kg: retailRef.normalized_usd_per_kg,
        bulk_usd_per_kg: bulkRef.normalized_usd_per_kg,
        premium: retailPremium,
        retail_form: retailRef.form,
        bulk_form: bulkRef.form,
      });
    }
  }
  rows.sort((a, b) => b.premium - a.premium);
  return typeof limit === 'number' ? rows.slice(0, limit) : rows;
}

/**
 * Element coverage tally by fluctuation `data_quality`. 'none' counts catalog
 * elements that have no fluctuation entry or zero observations.
 */
export function getCoverageTally(): CoverageTally {
  ensureVerified();
  const fluctuations = loadFluctuationsFile().elements;
  const tally: CoverageTally = { rich: 0, moderate: 0, sparse: 0, none: 0 };
  for (const el of loadElementCatalog()) {
    const f = fluctuations[el.symbol];
    if (!f || f.observation_count === 0) {
      tally.none += 1;
    } else {
      tally[f.data_quality] += 1;
    }
  }
  return tally;
}

/**
 * Per-element price-data coverage (symbol, name, category, quality grade, and
 * observation count) in catalog order: the rows behind the data-coverage grid.
 * `quality` is 'none' when an element has no fluctuation entry or zero
 * observations.
 */
export function getElementCoverage(): ElementCoverage[] {
  ensureVerified();
  const fluctuations = loadFluctuationsFile().elements;
  return loadElementCatalog().map((el) => {
    const f = fluctuations[el.symbol];
    const observations = f?.observation_count ?? 0;
    const quality = !f || observations === 0 ? 'none' : f.data_quality;
    return {
      symbol: el.symbol,
      name: el.name,
      category: el.category,
      quality,
      observations,
    };
  });
}

/**
 * China-export-control counts per element category, in `CATEGORY_ORDER`: the
 * rows behind the market-structure bars. `controlled` counts elements with
 * `cn_export_control === true`.
 */
export function getControlByCategory(): CategoryControl[] {
  ensureVerified();
  const elements = loadElementCatalog();
  return CATEGORY_ORDER.map((category) => {
    const inCat = elements.filter((e) => e.category === category);
    return {
      category,
      controlled: inCat.filter((e) => e.cn_export_control).length,
      total: inCat.length,
    };
  });
}

/**
 * Element counts by Chinese export-control posture (restricted/monitored/normal)
 * and current regulatory state (active/suspended/none): the dashboard
 * regulatory snapshot (Prompt 17). Both breakdowns partition all catalog
 * elements; counts come straight from the catalog (no fabrication).
 */
export function getRegulatorySnapshot(): RegulatorySnapshot {
  ensureVerified();
  const elements = loadElementCatalog();
  const snapshot: RegulatorySnapshot = {
    export_control: { restricted: 0, monitored: 0, normal: 0 },
    regulatory: { active: 0, suspended: 0, none: 0 },
    total: elements.length,
  };
  for (const el of elements) {
    snapshot.export_control[el.export_control_status] += 1;
    snapshot.regulatory[el.regulatory_status] += 1;
  }
  return snapshot;
}
