#!/usr/bin/env python3
"""Count price observations by source_type and write a breakdown for Jekyll.

Reads every ``_data/price_history/*.yml`` file, counts how many observations
fall into each ``source_type`` bucket, and writes the result to
``_data/source_breakdown.yml`` for inclusion on the methodology page.

The breakdown reflects the actual content of the price history. Categories
are: ``public_listing``, ``community_submission``, ``supplier_quote``,
``invoice``, ``benchmark``, ``aggregate``. Observations without a
``source_type`` tag fall into ``uncategorised`` so a maintainer notices
gaps. The breakdown is regenerated by hand or as part of the data pipeline,
not as a Liquid include — Jekyll reads the resulting YAML at build time.
"""

from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
HISTORY_DIR = PROJECT_ROOT / "_data" / "price_history"
OUTPUT_FILE = PROJECT_ROOT / "_data" / "source_breakdown.yml"

# Order shown on the page. "uncategorised" is appended only if non-zero.
DISPLAY_ORDER = (
    "public_listing",
    "community_submission",
    "supplier_quote",
    "invoice",
    "benchmark",
    "aggregate",
)

LABELS = {
    "public_listing": "Public listings",
    "community_submission": "Community submissions",
    "supplier_quote": "Supplier quotes",
    "invoice": "Invoices",
    "benchmark": "Benchmarks / price-reporting agencies",
    "aggregate": "Aggregates (medians)",
    "uncategorised": "Uncategorised (legacy)",
}

DESCRIPTIONS = {
    "public_listing": "Prices observed on a public seller storefront or marketplace listing — retailers, eBay sellers, Alibaba pages. Collected with seller, date, form, purity, and URL recorded.",
    "community_submission": "Prices submitted by readers through the price-update GitHub issue template, reviewed and approved by the maintainer, then merged via pull request. Two human checkpoints before publication.",
    "supplier_quote": "Prices supplied directly by suppliers who have opted in to the outreach registry. The maintainer reads the reply and runs the structured intake; no scraping, no auto-emailing.",
    "invoice": "Prices extracted from uploaded purchase invoices. Highest trust tier.",
    "benchmark": "Prices from recognised price-reporting agencies (LME, Fastmarkets, Shanghai Metals Market, Argus, USGS, IMARC, BusinessAnalytiq).",
    "aggregate": "Median-of-individual-observations rows generated when more than one source agrees on a given day.",
    "uncategorised": "Observations imported before source_type was required. Run scripts/backfill_source_types.py to assign them a category.",
}


def build_breakdown() -> dict:
    counts: dict[str, int] = {}
    total = 0
    for path in sorted(HISTORY_DIR.glob("*.yml")):
        with path.open("r", encoding="utf-8") as fh:
            data = yaml.safe_load(fh) or {}
        for obs in data.get("observations") or []:
            if not isinstance(obs, dict):
                continue
            st = obs.get("source_type") or "uncategorised"
            counts[st] = counts.get(st, 0) + 1
            total += 1

    items = []
    keys = list(DISPLAY_ORDER)
    if counts.get("uncategorised", 0) > 0:
        keys.append("uncategorised")
    seen = set()
    for k in keys:
        n = counts.get(k, 0)
        seen.add(k)
        if n == 0 and k != "uncategorised":
            # Keep zero-count buckets so the page lists every category we
            # actively support, even when the count is currently zero.
            pct = 0.0
        else:
            pct = round((n / total) * 100, 1) if total else 0.0
        items.append(
            {
                "source_type": k,
                "label": LABELS[k],
                "description": DESCRIPTIONS[k],
                "count": n,
                "percent": pct,
            }
        )

    # Surface any unknown source_type we don't recognise so it's not hidden.
    for k, n in counts.items():
        if k in seen:
            continue
        items.append(
            {
                "source_type": k,
                "label": k,
                "description": "(unrecognised source_type — extend scripts/source_breakdown.py)",
                "count": n,
                "percent": round((n / total) * 100, 1) if total else 0.0,
            }
        )

    return {
        "generated_on": date.today().isoformat(),
        "total_observations": total,
        "by_source_type": items,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--print",
        action="store_true",
        help="Print the breakdown to stdout instead of writing the YAML file.",
    )
    args = parser.parse_args(argv)

    breakdown = build_breakdown()

    if args.print:
        yaml.safe_dump(breakdown, sys.stdout, sort_keys=False, allow_unicode=True)
        return 0

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_FILE.open("w", encoding="utf-8") as fh:
        fh.write(
            "# Generated by scripts/source_breakdown.py.\n"
            "# Counts observations in _data/price_history/*.yml by source_type.\n"
            "# Re-run after data changes; do not hand-edit.\n"
        )
        yaml.safe_dump(breakdown, fh, sort_keys=False, allow_unicode=True)
    print(
        f"  wrote {OUTPUT_FILE.relative_to(PROJECT_ROOT)} — "
        f"{breakdown['total_observations']} observation(s) across "
        f"{len(breakdown['by_source_type'])} categor{'y' if len(breakdown['by_source_type'])==1 else 'ies'}."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
