/**
 * The "Data sources breakdown" table on /methodology, re-implemented from
 * `_data/source_breakdown.yml` (legacy: a Liquid loop over
 * `site.data.source_breakdown`). Server-rendered; the page splices it in where
 * the original Liquid block sat, so the surrounding methodology prose is intact.
 *
 * Reflects what the data actually contains (regenerated by
 * scripts/source_breakdown.py). No fabricated counts. Composes the shared Table
 * primitives (Prompt 12).
 */
import { Table, THead, TBody, TR, TH, TD } from '@/components/ui';
import { formatDate } from '@/lib/format';
import type { SourceBreakdown } from '@/lib/types';

export function SourceBreakdownTable({ breakdown }: { breakdown: SourceBreakdown }) {
  return (
    <div className="my-6">
      <p className="mb-3 text-sm italic text-fg-dim">
        Generated {formatDate(breakdown.generated_on)} from{' '}
        <span className="font-mono tabular-nums">
          {breakdown.total_observations}
        </span>{' '}
        observations.
      </p>

      <Table>
        <THead>
          <TR hover={false}>
            <TH>Source type</TH>
            <TH numeric>Count</TH>
            <TH numeric>Share</TH>
            <TH>Description</TH>
          </TR>
        </THead>
        <TBody>
          {breakdown.by_source_type.map((row) => (
            <TR key={row.source_type}>
              <TD className="whitespace-nowrap font-semibold">
                <span className="text-fg">{row.label}</span>
              </TD>
              <TD numeric>{row.count}</TD>
              <TD numeric>{row.percent}%</TD>
              <TD className="leading-relaxed">{row.description}</TD>
            </TR>
          ))}
        </TBody>
      </Table>
    </div>
  );
}
