/**
 * The "Data sources breakdown" table on /methodology, re-implemented from
 * `_data/source_breakdown.yml` (legacy: a Liquid loop over
 * `site.data.source_breakdown`). Server-rendered; the page splices it in where
 * the original Liquid block sat, so the surrounding methodology prose is intact.
 *
 * Reflects what the data actually contains (regenerated by
 * scripts/source_breakdown.py) — no fabricated counts.
 */
import type { SourceBreakdown } from '@/lib/types';

export function SourceBreakdownTable({ breakdown }: { breakdown: SourceBreakdown }) {
  return (
    <div className="my-6">
      <p className="mb-3 text-sm italic text-fg-dim">
        Generated {breakdown.generated_on} from{' '}
        <span className="font-mono tabular-nums">
          {breakdown.total_observations}
        </span>{' '}
        observations.
      </p>

      <div className="overflow-x-auto border border-border">
        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className="bg-surface text-left">
              <th className="border-b-2 border-border-strong px-3 py-2 text-2xs font-semibold uppercase tracking-wide text-fg-dim">
                Source type
              </th>
              <th className="border-b-2 border-border-strong px-3 py-2 text-right text-2xs font-semibold uppercase tracking-wide text-fg-dim">
                Count
              </th>
              <th className="border-b-2 border-border-strong px-3 py-2 text-right text-2xs font-semibold uppercase tracking-wide text-fg-dim">
                Share
              </th>
              <th className="border-b-2 border-border-strong px-3 py-2 text-2xs font-semibold uppercase tracking-wide text-fg-dim">
                Description
              </th>
            </tr>
          </thead>
          <tbody>
            {breakdown.by_source_type.map((row) => (
              <tr
                key={row.source_type}
                className="border-b border-border last:border-0 hover:bg-overlay"
              >
                <td className="whitespace-nowrap px-3 py-2 font-semibold text-fg">
                  {row.label}
                </td>
                <td className="px-3 py-2 text-right font-mono tabular-nums text-fg-muted">
                  {row.count}
                </td>
                <td className="px-3 py-2 text-right font-mono tabular-nums text-fg-muted">
                  {row.percent}%
                </td>
                <td className="px-3 py-2 leading-relaxed text-fg-muted">
                  {row.description}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
